### ISSUE TITLE
HTML parsing error

### ISSUE THREAD

**Issue by tommeagher** [tommeagher/irescraper#5]
Getting an error now. I'm guessing this may have be related to IRE.org moving to Wordpress from Django. Perhaps the pages are laid out slightly differently now?

```
Traceback (most recent call last):
  File "sched.py", line 257, in <module>
    main()
  File "sched.py", line 243, in main
    conf.scrape()
  File "sched.py", line 88, in scrape
    first_day = tree.xpath('body/div/div[2]/section/section[2]/article/div/ul/li/a')[0].text
IndexError: list index out of range
```

**Comment by joemfox** [comment]
Working on this. The pages _are_ laid out slightly differently now!

**Comment by tommeagher** [comment]
That's what I thought. I'm glad it's not just me. It looks like IRE is now hosting it's own version of the CSV on Github, which is cool: https://github.com/ireapps/nicar-2019-schedule
So this issue, and this scraper, may not be all that necessary anymore. So don't kill yourself on this. But if you figure it out and it's a minor fix, the help would of course be appreciated.

**Comment by joemfox** [comment]
Ha, that does pretty much solve it. Still submitted a PR: https://github.com/tommeagher/irescraper/pull/6

**Comment by thejqs** [comment]
This is what I get for not looking back at Twitter earlier. I ... I worked something up for this, too, including a port to Python 3. Y'know, because.

**Comment by tommeagher** [comment]
You guys! hahaha.
Thanks to you both. It speaks volumes about the @ireapps community that you two took the time and trouble to update this. I merged @joemfox's PR, but I'll take a look at yours, Jacob and merge as well, probably tomorrow.

**Comment by thejqs** [comment]
All good, @tommeagher. If there's something in there you can use, wonderful. No need to incorporate it just because. It is quite literally slapped together. 

I'm just going to keep being amused by this for a while.
